### ISSUE TITLE
Filter check command to show only updates within patch, minor or major version

### ISSUE THREAD

**Issue by ComLock** [versioneye/veye#23]
Say I want to do easy upgrades first, listing only outdated gems where version_current is within patch version.

Something like:
```bash
veye check Gemfile.lock --patch
```
```bash
veye check Gemfile.lock --minor
```
```bash
veye check Gemfile.lock --major
```

http://semver.org/

**Comment by timgluz** [comment]
Hi, that's good idea.

**Comment by timgluz** [comment]
Note to myself: 

there's Semverly lib that would make this filtering super easy;

**Comment by timgluz** [comment]
Done;
