### ISSUE TITLE
libv8-3.16.14.9 gem yanked from rubygems, but still avail on versioneye

### ISSUE THREAD

**Issue by ComLock** [versioneye/veye#24]
```sh
veye check Gemfile.lock
```
Says libv8-3.16.14.8 is outdated with current_version libv8-3.16.14.9

There is a libv8-3.16.14.9 tag/release https://github.com/cowboyd/libv8/releases

But it was yanked:
https://github.com/cowboyd/libv8/issues/175

So rubygems has 3.16.14.8 as latest:
https://rubygems.org/gems/libv8

So
```sh
bundle oudated
````
does not report 3.16.14.8 as outdated

Is it possible to yank releases on versioneye ?

**Comment by reiz** [comment]
I just removed the yanked version. See here: https://www.versioneye.com/ruby/libv8/3.16.14.8 

Currently the admin (me) and the selected users can edit product pages. If you are a core committer of libv8 I can give you rights for the product page, so that you can edit the details. 

/cc @timgluz
