### ISSUE TITLE
projects list does not show privacy setting correctly

### ISSUE THREAD

**Issue by ComLock** [versioneye/veye#26]
be veye projects list --format=md
# Project's information

index|name           |project_key           |project_type|private|period|source|dependencies|outdated|created
-----|---------------|----------------------|------------|-------|------|------|------------|--------|----------------
1    |whatever|rubygem_gemfile_lock_2|RubyGem     |       |daily |API   |130         |4       |01.07.2015-13:28

**Comment by reiz** [comment]
The API request 

```
GET /v2/projects/<PROJECT_ID>?<API_KEY>
```

returns a JSON object which contains the fields `public` and `private_scm`. The `public` field just says if the project on VersionEye is public or not. If it is public on VersionEye everybody who knows the URL to the project can see the dependency & license tab. The `private_scm` field says if it is a private project on GitHub or Bitbucket. @timgluz Maybe the wrong field is used from the client?

**Comment by timgluz** [comment]
i'll check into it.

**Comment by timgluz** [comment]
Thanks for reporting it - it was simple bug in code indeed; it's now fixed and will release update version soon.

**Comment by reiz** [comment]
+1 

I'm currently deploying the new API. It offers more options for the file upload.
