### ISSUE TITLE
Add cmds to manage project collaborators

### ISSUE THREAD

**Issue by timgluz** [versioneye/veye#28]
As user, i want to see and manage project collaborators without visiting VersionEye page;

Example workflow:
```
$> veye collaborators <ProjectID> - lists project collaborators
$> veye collaborators <ProjectID> add <email> - adds new collaborator
$> veye collaborators <ProjectID> remove <email> - removes collaborator
```

**Comment by reiz** [comment]
+1 

I will add some Endpoints to the API for that.

**Comment by timgluz** [comment]
Will remove from the 0.2 milestone as no such API and next milestone will just be dependency updates and features required for auto-updater
