### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by reiz** [versioneye/veye#37]
@timgluz There are releases at RubyGems but no tags on this repo. Would be awesome to have here tags as well ;) 

```
git tag -a v0.1.0 -m 'My lovely tag` 
git push origin master --tags 
```

**Comment by timgluz** [comment]
THANKS,  i will add it into build task.

**Comment by timgluz** [comment]
Now every release will have tags attached, like v0.1 has: [https://github.com/versioneye/veye/releases](https://github.com/versioneye/veye/releases)

**Comment by reiz** [comment]
Awesome. No we can keep the change logs at the tags, with GitHubs new release feature ;-) I'm using it here: https://github.com/versioneye/versioneye_maven_plugin/releases
