### ISSUE TITLE
veye create should create a versioneye.properties file

### ISSUE THREAD

**Issue by reiz** [versioneye/veye#39]
I just run 

```
veye projects upload Gemfile
```

and it worked perfectly. It created a new project at VersionEye and printed out the project details and the dependencies. 

Updating the project works now like this: 

```
veye projects update rubygem_gemfile_3 Gemfile
```

That works, but it's not intuitiv. Over all my projects I have at least 20 different Gemfiles. How should I know next week which project is which `rubygem_gemfile_X`? It would be nice if `veye projects upload` would create a `versioneye.properties` file in the root of my project and store the project ID from VersionEye. The file content could look like that: 

```
# Properties for https://www.VersionEye.com
# Wed May 20 10:50:29 CEST 2015
project_id=555c4b613f85jjf11e061000004
```

The [VersionEye Maven Plugin](https://github.com/versioneye/versioneye_maven_plugin) and the [VersionEye SBT Plugin](https://github.com/versioneye/versioneye_sbt_plugin) are doing it that way. Would be nice if **veye** would follow the same pattern. 

Then the update process would look like this: 

```
veye projects update Gemfile
```

That command would read the project ID from the file and update the project with the current dependencies. Much easier and I don't have to remember any names and IDs ;-)

**Comment by reiz** [comment]
I **veye** is supporting the `versioneye.properties` file I could create a project with the VersionEye Maven Plugin and later update the same project with **veye**. That would be awesome :-)

**Comment by timgluz** [comment]
Well, i've thought about it. Specially when i was drafting implementation for auto-update.

My idea was to use bigger json file in project, which also allows to keep not only project id, but also muting some dependencies, allowing autoupdates for some packages.

veye.json looks like something like this
```
{
project : { id: "X", name: "x of Y", tags: "x,y,z"} //project meta-data
dependencies: [{name: "z", mute: false; autoupdate: true | "< 2.10" }] // dependency level settings: muting. etc
settings: {format: 'csv'} // default client settings to override global client settings: format, apiKey, etc
} 
```

**Comment by timgluz** [comment]
Is versioneye.properties some fancy Java properties format?

**Comment by reiz** [comment]
`.properties` files are supported from Java, but it's a simple Variable = Value file like 

```
VARIABLE=VALUE
my_var=my_value
name=Robert Reiz 
```

`veye.json` is fine as well. But I wouldn't store too much in it. Muting dependencies is something what happens on the server side. See [here](http://blog.versioneye.com/2015/07/22/improved-mute-feature-2/)

**Comment by timgluz** [comment]
ok, i've finally some time for `veye` .

@reiz What's the feedback from developers about autogenerated file in project? Did you add any lines to documentation that warns about adding a new file into project folder?

**Comment by timgluz** [comment]
ok, i've done rewriting the `check` command

The new `check` command scans the folder (by default current working dir) and creates new projects for each of supported project files and saves their ids into veye.json file. So if user re-runs the command, then it tries to re-use project_keys from the veye.json and will update existing project file.

I'll do some testing with real projects tomorrow and if everything works well, then i'll release version `0.2`.

**Comment by reiz** [comment]
Hi @timgluz. That looks good to me. As lon there are only project ids in the json file it's not a big issue. That's not sensitive data and the users don't have a problem with it. The API key is more sensitive.
