### ISSUE TITLE
Specifying filename for GitHub import

### ISSUE THREAD

**Issue by reiz** [versioneye/veye#40]
I saw [here](https://raw.githubusercontent.com/wiki/versioneye/veye/cli/github.md) that it's possible to specify the branch at a GitHub import. How about the file name?

**Comment by timgluz** [comment]
hi,

`veye github import` accepts `--file` argument, which allows to specify project file name.

**Comment by timgluz** [comment]
i'll add example into documentation.

**Comment by reiz** [comment]
@timgluz Cool. Thx.
