### ISSUE TITLE
Fails to create project

### ISSUE THREAD

**Issue by bootstraponline** [versioneye/veye#50]
> $ veye projects upload Podfile
> error: wrong number of arguments (given 7, expected 3..5)

**Comment by bootstraponline** [comment]
```ruby
def self.upload(api_key, filename, org_name = 'private', team_name = nil, options)

Veye::Project::Check.upload(api_key, filename, org_name, options[:team], is_temp, visibility, options)
```

There are no tests to check if the CLI bin actually works or not. The method signature changed yet the bin file wasn't updated.

**Comment by timgluz** [comment]
Thanks for reporting this;
